[package]
name = "system_ts"
authors = ["Chien Zhang (zqy0224@live.com)"]
description = "Time & timer service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rinlib = { path = "../../rinlib" }
