[package]
name = "kzios-boot"
authors = ["Chien Zhang <zqy0224@live.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = "0.7"
k210-pac = "0.2"
k210-hal = "0.2"