[package]
name = "erhino_kernel"
version = "0.1.0"
authors = [ "Chien Zhang (zqy0224@live.com)"]
description = "kernel.bin"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erhino_shared = { path = "../../shared"}
riscv = "0.8"
spin = "0.9"
lazy_static = { version = "1.4", features = ["spin_no_std"]}
buddy_system_allocator = { version = "0.8", features = ["const_fn", "use_spin"] }